/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techquizapp.gui;

import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import techquizapp.dao.PerformanceDAO;
import techquizapp.dao.QuestionDAO;
import techquizapp.pojo.Answer;
import techquizapp.pojo.AnswerStore;
import techquizapp.pojo.Exam;
import techquizapp.pojo.Performance;
import techquizapp.pojo.Question;
import techquizapp.pojo.QuestionStore;
import techquizapp.pojo.UserProfile;

/**
 *
 * @author Pushpendra
 */
public class TakeTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form TakeTestFrame
     */
    Color oldColor;
    int qno,pos=0;
    QuestionStore qStore;
    AnswerStore aStore;
    Exam examobj;
    Clocks c;
    
    public TakeTestFrame() {
        initComponents();
        oldColor=jlblLogout.getForeground();
        this.setLocationRelativeTo(null);
        jlblUserName.setText("Hello "+UserProfile.getUsername());
        qno=1;
        jlblquestion.setText("Question No:"+qno);
        qStore=new QuestionStore();
        aStore=new AnswerStore();
        c=new Clocks();
        c.start();
    }
    
    public TakeTestFrame(Exam exam)
    {
        this();
        examobj=exam;
        jlblTitle.setText(examobj.getLanguage().toUpperCase()+" PAPER");
        loadQuestions();
        showQuestions();
    }

    private void loadQuestions()
    {
        try
        {
            ArrayList<Question> quesList=new ArrayList<>();
            quesList=QuestionDAO.getQuestionsByExamId(examobj.getExamId());
            for(Question q:quesList)
            {
                qStore.addQuestion(q);
                
            }
            System.out.println(qStore);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "DB Error","Edit Question Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    private void showQuestions()
    {
        Question ques=qStore.getQuestion(pos);
        buttonGroup1.clearSelection(); 
        txtQuestion.setText(ques.getQuestion());
        jrbOption1.setText(ques.getAnswer1());
        jrbOption2.setText(ques.getAnswer2());
        jrbOption3.setText(ques.getAnswer3());
        jrbOption4.setText(ques.getAnswer4());
        Answer ans=aStore.getAnswerByQno(qno);
        if(ans==null)
        {
            return;
        }
        String str=ans.getChosenAnswer();
        switch(str)
        {
            case "Answer1":
                jrbOption1.setSelected(true);
                break;
            case "Answer2":
                jrbOption2.setSelected(true);
                break;
            case "Answer3":
                jrbOption3.setSelected(true);
                break;
            case "Answer4":
                jrbOption4.setSelected(true);
                break;
        }
        
    }
    
    private String getuserAnswer()
    {
        if(jrbOption1.isSelected())
            return "Answer1";
        else if(jrbOption2.isSelected())
            return "Answer2";
        else if(jrbOption3.isSelected())
            return "Answer3";
        else if(jrbOption4.isSelected())
            return "Answer4";
        else
            return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jlblquestion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jlblUserName = new javax.swing.JLabel();
        jrbOption1 = new javax.swing.JRadioButton();
        jrbOption2 = new javax.swing.JRadioButton();
        jrbOption3 = new javax.swing.JRadioButton();
        jrbOption4 = new javax.swing.JRadioButton();
        btnDone = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jlblLogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jlblTitle.setBackground(new java.awt.Color(0, 0, 0));
        jlblTitle.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jlblTitle.setForeground(new java.awt.Color(0, 204, 204));
        jlblTitle.setText("JAVA PAPER");

        jlblquestion.setBackground(new java.awt.Color(0, 0, 0));
        jlblquestion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblquestion.setForeground(new java.awt.Color(0, 204, 204));
        jlblquestion.setText("Question No:");

        txtQuestion.setEditable(false);
        txtQuestion.setColumns(20);
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 204, 204));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jlblUserName.setBackground(new java.awt.Color(0, 0, 0));
        jlblUserName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblUserName.setForeground(new java.awt.Color(0, 204, 204));
        jlblUserName.setText("Hello");

        jrbOption1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbOption1);
        jrbOption1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOption1.setForeground(new java.awt.Color(0, 204, 204));
        jrbOption1.setText("jRadioButton1");

        jrbOption2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbOption2);
        jrbOption2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOption2.setForeground(new java.awt.Color(0, 204, 204));
        jrbOption2.setText("jRadioButton2");

        jrbOption3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbOption3);
        jrbOption3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOption3.setForeground(new java.awt.Color(0, 204, 204));
        jrbOption3.setText("jRadioButton3");

        jrbOption4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbOption4);
        jrbOption4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOption4.setForeground(new java.awt.Color(0, 204, 204));
        jrbOption4.setText("jRadioButton4");

        btnDone.setBackground(new java.awt.Color(0, 0, 0));
        btnDone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDone.setForeground(new java.awt.Color(0, 204, 204));
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnPrevious.setBackground(new java.awt.Color(0, 0, 0));
        btnPrevious.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(0, 204, 204));
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(0, 0, 0));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(0, 204, 204));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jlblLogout.setBackground(new java.awt.Color(0, 0, 0));
        jlblLogout.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlblLogout.setForeground(new java.awt.Color(0, 204, 204));
        jlblLogout.setText("Logout");
        jlblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblLogoutMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/questionpaper4.jpg"))); // NOI18N

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClock.setForeground(new java.awt.Color(0, 204, 204));

        jLabel2.setText("jLabel2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("TIME LEFT :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jlblquestion)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jrbOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jrbOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jlblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblLogout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(76, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(244, 244, 244)))
                                .addGap(119, 119, 119)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUserName)
                    .addComponent(jlblLogout))
                .addGap(18, 18, 18)
                .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblquestion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbOption4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        PaperSelectionFrame choosePaper=new PaperSelectionFrame();
        choosePaper.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       String chosenAnswer=getuserAnswer();
       if(chosenAnswer!=null)
       {
           Question ques=qStore.getQuestionByQno(qno);
           String correctAnswer=ques.getCorrectAnswer();
           Answer ans=new Answer(examobj.getExamId(),examobj.getLanguage(),qno,chosenAnswer,correctAnswer);
           Answer attempted=aStore.getAnswerByQno(qno);
           if(attempted==null)
           {
               aStore.addAnswer(ans);
           }
           else
           {
               String previous=attempted.getChosenAnswer();
               if(chosenAnswer.equals(previous)==false)
               {
                   int apos=aStore.removeAnswer(attempted);
                   aStore.setAnswerAt(apos, ans);
               }
           }
           
       }
       pos++;
        if(pos>=qStore.getCount())
        {
            pos=0; 
        }
        
        qno++;
        if(qno>qStore.getCount())
        {
            qno=1;
        }
        jlblquestion.setText("Question No: "+qno);
        showQuestions();
       
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
      
        String chosenAnswer=getuserAnswer();
       if(chosenAnswer!=null)
       {
           Question ques=qStore.getQuestionByQno(qno);
           String correctAnswer=ques.getCorrectAnswer();
           Answer ans=new Answer(examobj.getExamId(),examobj.getLanguage(),qno,chosenAnswer,correctAnswer);
           Answer attempted=aStore.getAnswerByQno(qno);
           if(attempted==null)
           {
               aStore.addAnswer(ans);
           }
           else
           {
               String previous=attempted.getChosenAnswer();
               if(chosenAnswer.equals(previous)==false)
               {
                   int apos=aStore.removeAnswer(attempted);
                   aStore.setAnswerAt(apos, ans);
               }
           }
           
       }
       pos--;
        if(pos<0)
        {
            pos=qStore.getCount()-1; 
        }
        
        qno--;
        if(qno<=0)
        {
            qno=qStore.getCount();
        }
        jlblquestion.setText("Question No: "+qno);
        showQuestions();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        c.stop();
        String chosenAnswer=getuserAnswer();
       if(chosenAnswer!=null)
       {
           Question ques=qStore.getQuestionByQno(qno);
           String correctAnswer=ques.getCorrectAnswer();
           Answer ans=new Answer(examobj.getExamId(),examobj.getLanguage(),qno,chosenAnswer,correctAnswer);
           Answer attempted=aStore.getAnswerByQno(qno);
           if(attempted==null)
           {
               aStore.addAnswer(ans);
           }
           else
           {
               String previous=attempted.getChosenAnswer();
               if(chosenAnswer.equals(previous)==false)
               {
                   int apos=aStore.removeAnswer(attempted);
                   aStore.setAnswerAt(apos, ans);
               }
           }
           
       }
       int right=0, wrong=0;
       for(Question ques:qStore.getAllQuestions())
       {
           int qno=ques.getQno();
           Answer ans=aStore.getAnswerByQno(qno);
           if(ans==null)
               continue;
           String attemptedAnswer=ans.getChosenAnswer();
           String correctAnswer=ans.getCorrectAnswer();
           if(attemptedAnswer.equals(correctAnswer))
               ++right;
           else
               ++wrong;
           
       }
        StringBuilder sb=new StringBuilder();
        sb.append("\nRight answers : "+right);
        sb.append("\nWrong answers: "+wrong);
        sb.append("\nUnattempted: "+(qStore.getCount()-(right+wrong)));
        JOptionPane.showMessageDialog(null, sb.toString(),"Result",JOptionPane.INFORMATION_MESSAGE);
        try
        {
            Performance perf=new Performance(UserProfile.getUsername(),examobj.getExamId(),right,wrong,(qStore.getCount()-(right+wrong)),(double)right/qStore.getCount()*100,examobj.getLanguage());
            PerformanceDAO.addPerformance(perf);
            JOptionPane.showMessageDialog(null, "Result Saved\nThankyou for the test","Done",JOptionPane.INFORMATION_MESSAGE);
            PaperSelectionFrame paperFrame=new PaperSelectionFrame();
            paperFrame.setVisible(true);
            this.dispose();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "DB Error","TakeTest Error",JOptionPane.ERROR_MESSAGE);
        }
       
       
       
    }//GEN-LAST:event_btnDoneActionPerformed

    private void jlblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblLogoutMouseClicked
        LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlblLogoutMouseClicked

    private void jlblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblLogoutMouseEntered
        jlblLogout.setForeground(Color.white);
    }//GEN-LAST:event_jlblLogoutMouseEntered

    private void jlblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblLogoutMouseExited
        jlblLogout.setForeground(oldColor);
    }//GEN-LAST:event_jlblLogoutMouseExited

        class Clocks extends Thread{
        int time=0;
          int m=1,s=60,h=0;
       public void run(){
       while(true){
               Calendar date=Calendar.getInstance();
               date.setTime(new Date());
               date.set(Calendar.HOUR_OF_DAY, h);
               date.set(Calendar.MINUTE, m);
               date.set(Calendar.SECOND, s);
               date.set(Calendar.MILLISECOND, 0);
               Date da=date.getTime();
               SimpleDateFormat sdf=new SimpleDateFormat("HH:mm:ss");
               String str=sdf.format(da);
               
        try{
            Thread.sleep(1000);
            s=s-1;
            if(s==0){
                m=m-1;
                s=60;
                time=time+1;
            }
            
            //time=time+1000;
            lblClock.setText(str);
            }
            catch(InterruptedException ex){
                System.out.println(ex);
            }
           if(time==2){
               lblClock.setText("00:00:00");
               JOptionPane.showMessageDialog(null, " TIME IS FINISHED PRESS DONE TO SUBMIT EXAM","TIME OUT",JOptionPane.INFORMATION_MESSAGE);
               //doneTest();
               btnNext.setEnabled(false);
               btnPrevious.setEnabled(false);
               btnCancel.setVisible(false);
               jlblLogout.setVisible(false);
               break;
           }
       }
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblLogout;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JLabel jlblUserName;
    private javax.swing.JLabel jlblquestion;
    private javax.swing.JRadioButton jrbOption1;
    private javax.swing.JRadioButton jrbOption2;
    private javax.swing.JRadioButton jrbOption3;
    private javax.swing.JRadioButton jrbOption4;
    private javax.swing.JLabel lblClock;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables
}
